pipeline {
    agent { label 'ztec-201-STC' }

    parameters {
        string(name: 'BRANCH_NAME', defaultValue: 'feature/jenkins-pipeline-wdquery', description: 'Feature branch to checkout')
        string(name: 'application', defaultValue: 'MortgageApplication', description: 'Application Name filter')
        string(name: 'deployed_after', defaultValue: '*', description: 'starting time e.g. 20250911')
        string(name: 'deployed_before', defaultValue: '*', description: 'ending time e.g. 20250913')
        choice(name: 'environmentFilter', choices: ['*', 'EOLEB7-Integration', 'EOLEB7-Acceptance', 'EOLEB7-Production'], description: 'Environment name filter')
    }

    environment {
        wdEvidencesRoot = '/var/work/wazi_deploy_evidences_jenkins'
        wdEvidencesIndex = '/var/work/wazi_deploy_evidences_jenkins_index/'
        reportOutputDirectory = "${env.WORKSPACE}/REPORT-OUTPUT"
        reportFile = "${env.reportOutputDirectory}/deployment-inventory-report-${env.BUILD_ID}.txt"
        rendererFile = "${env.WORKSPACE}/Wazi_Deploy/Reporting/List-packages-by-timewindow-query/renderer.yml"
        templateFile = "${env.WORKSPACE}/Wazi_Deploy/Reporting/List-packages-by-timewindow-query/queryTemplate.yml"
    }

    stages {
        stage('Cleanup') {
            steps {
                echo 'Deleting workspace before build...'
                deleteDir()
            }
        }
        stage('Clone Repo') {
        steps {
            git(
                branch: "${params.BRANCH_NAME}",
                url: 'https://github.com/thadbeeraf/dbb.git',
                credentialsId: 'thadbeera-gtoken' 
            )
        }
    }

        stage('Prepare Directories') {
            steps {
                sh "mkdir -p ${env.reportOutputDirectory}"
            }
        }
        stage('Query') {
            steps {
                script {
                    echo "[INFO] wdEvidencesRoot   = ${env.wdEvidencesRoot}"
                    echo "[INFO] wdEvidencesIndex  = ${env.wdEvidencesIndex}"

                    sh 'pwd'
                    sh "ls -ld /var/work/wazi_deploy_evidences_jenkins_index/"

                    def CMD = """
                        wazideploy-evidence --indexFolder '${env.wdEvidencesIndex}' \
                        --dataFolder '${env.wdEvidencesRoot}' \
                        --template '${env.templateFile}' \
                        --output='${env.reportFile}' \
                        r env='${params.environmentFilter}' \
                        deployed_after='${params.deployed_after}' \
                        deployed_before='${params.before}' \
                        renderer='${env.rendererFile}'
                    """.trim().replaceAll("\n+", " ").replaceAll("\\s{2,}", " ")

                    echo "[INFO] Executing command : ${CMD}"
                    int rc = sh(script: CMD, returnStatus: true)

                    if (rc != 0) {
                        error("[WARNING] - Query Wazi Deploy index failed with return code ${rc}.")
                    }

                    echo "[INFO] Cleaning up invalid characters in report file..."
                    // Clean invalid or binary bytes while keeping UTF-8
                    sh """
                        iconv -f UTF-8 -t UTF-8 -c '${env.reportFile}' > '${env.reportFile}.clean' || cp '${env.reportFile}' '${env.reportFile}.clean'
                        mv '${env.reportFile}.clean' '${env.reportFile}'
                    """

                    echo "[INFO] - Query Wazi Deploy index completed. Report ${env.reportFile} generated and cleaned."
                }
            }
            post {
                success {
                    archiveArtifacts artifacts: 'REPORT-OUTPUT/*.txt', onlyIfSuccessful: true
                }
            }
        }
    }
}    